require:
  - rubocop-rspec
  - rubocop-rails

Layout/LineLength:
  Max: 120

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  # Removed as it stops Rubocop from looking at any files.
  #  Include:
  #    - '**/Rakefile'
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
  TargetRubyVersion: 3.1

Style/RedundantSelf:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false

Metrics/ModuleLength:
  Exclude:
    - "spec/*/**/*_spec.rb"

RSpec/DescribedClass:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context', 'feature', 'define', 'shared_examples', 'factory']

# I like to use the description 'scenario' in feature specs.
RSpec/Capybara:
   Exclude:
    - spec/system/**/*_spec.rb

# Feature specs are written in a style similar to Cucumber.  As such they have more lines than Rubocop likes.
RSpec/ExampleLength:
  Exclude:
    - spec/system/**/*_spec.rb

# Testing of expectations is often moved to a separate method to make the code cleaner.
RSpec/NoExpectationExample:
  Exclude:
    - spec/system/**/*_spec.rb

RSpec/Capybara/FeatureMethods:
  Enabled: false
